import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "../provider/sessionProvider";
import { verifySession } from "../lib/dal";
import { getSession } from "../lib/session";
// import { getSession } from "./lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "next-auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
