import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "./lib/provider";
import { verifySession } from "./lib/dal";
import { getSession } from "./lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "next-auth",
  description: "Generated by create next app",
};

const session = getSession();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
